// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:4e919465-4c88-4d24-a796-07aa8ed5f651",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_0L7bMJ7X3",
    "aws_user_pools_web_client_id": "1j0rinnvdjupej1j9bl4u4te46",
    "aws_user_files_s3_bucket": "ieltsnoidaallimages1",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
